import importlib.util
import logging
import os
from pathlib import Path
from typing import Any, Dict, Optional

from logger import setup_logging
from unpack_volume import maybe_unpack

# Initialize logging configuration
setup_logging()

# Unpack Flash deployment artifacts if running in Flash mode
# This is a no-op for Live Serverless and local development
maybe_unpack()

logger = logging.getLogger(__name__)


def _load_generated_handler() -> Optional[Any]:
    """Load Flash-generated handler if available (deployed QB mode).

    Checks for a handler_<resource_name>.py file generated by the flash
    build pipeline. These handlers accept plain JSON input without
    FunctionRequest/cloudpickle serialization.

    Returns:
        Handler function if generated handler found, None otherwise.
    """
    resource_name = os.getenv("FLASH_RESOURCE_NAME")
    if not resource_name:
        return None

    handler_file = Path(f"/app/handler_{resource_name}.py")
    if not handler_file.exists():
        return None

    spec = importlib.util.spec_from_file_location(f"handler_{resource_name}", handler_file)
    if not spec or not spec.loader:
        logger.warning("Failed to create module spec for %s", handler_file)
        return None

    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except ImportError as e:
        logger.warning(
            "Generated handler %s failed to import (missing dependency: %s). "
            "Falling back to FunctionRequest handler. "
            "Deploy with --use-local-flash to include latest runpod_flash.",
            handler_file,
            e,
        )
        return None
    except Exception as e:
        logger.warning(
            "Generated handler %s failed to load: %s. Falling back to FunctionRequest handler.",
            handler_file,
            e,
        )
        return None

    generated = getattr(mod, "handler", None)
    if generated:
        logger.info("Loaded generated handler from %s", handler_file)
    return generated


# Try generated handler first (plain JSON mode for deployed QB endpoints)
_generated = _load_generated_handler()

if _generated:
    handler = _generated
else:
    # Fallback: original FunctionRequest handler (backward compatible)
    from runpod_flash.protos.remote_execution import FunctionRequest, FunctionResponse
    from remote_executor import RemoteExecutor

    async def handler(event: Dict[str, Any]) -> Dict[str, Any]:
        """RunPod serverless function handler with dependency installation."""
        output: FunctionResponse

        try:
            executor = RemoteExecutor()
            input_data = FunctionRequest(**event.get("input", {}))
            output = await executor.ExecuteFunction(input_data)

        except Exception as error:
            output = FunctionResponse(
                success=False,
                error=f"Error in handler: {str(error)}",
            )

        return output.model_dump()  # type: ignore[no-any-return]


# Start the RunPod serverless handler (only available on RunPod platform)
if __name__ == "__main__":
    import runpod

    runpod.serverless.start({"handler": handler})
